In [2]:
import pandas as pd
import numpy as np

In [7]:
labels = ['a', 'b', 'c']
my_list = [10, 20, 30]
arr = np.array([10, 20, 30])
d = {1: 10, 2: 20, 3: 30}

In [10]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [11]:
pd.Series(my_list, index=labels)

a    10
b    20
c    30
dtype: int64

In [ ]:
pd.Series(arr)

In [14]:
data ={
    'Name' : ['Alice', 'Bob', 'Charlie'],
    'Age' : [25, 30, 35],
    'City'  : ['New York', 'Los Angeles', 'Chicago'],
    'Salary' : [50000, 60000, 70000]
}

df = pd.DataFrame(data)
df

      Name  Age         City  Salary
0    Alice   25     New York   50000
1      Bob   30  Los Angeles   60000
2  Charlie   35      Chicago   70000

In [ ]:
data_list = [
    ['Alice', 25, 'New York', 50000],
    ['Bob', 30, 'Los Angeles', 60000],
    ['Charlie', 35, 'Chicago', 70000]
]
df2 = pd.DataFrame(data_list)
df2

         0   1            2      3
0    Alice  25     New York  50000
1      Bob  30  Los Angeles  60000
2  Charlie  35      Chicago  70000

In [ ]:
#conclusion: The code above demonstrates how to create a pandas Series and DataFrame using different data structures such as lists, arrays, and dictionaries. It also shows how to specify custom indices for the Series. The DataFrame is created from both a dictionary and a list of lists, showcasing the flexibility of pandas in handling various data formats.

In [22]:
df2["Designation"] = ["Manager", "Engineer", "Analyst"]
df2

         0   1            2      3 Designation
0    Alice  25     New York  50000     Manager
1      Bob  30  Los Angeles  60000    Engineer
2  Charlie  35      Chicago  70000     Analyst

In [29]:
df2.drop(["Designation"],axis=1)

         0   1            2      3
0    Alice  25     New York  50000
1      Bob  30  Los Angeles  60000
2  Charlie  35      Chicago  70000

In [ ]:
df.loc[[0,1]]  # Accessing the first two rows of the DataFrame using label-based indexing

    Name  Age         City  Salary
0  Alice   25     New York   50000
1    Bob   30  Los Angeles   60000

In [32]:
df.loc[[0,1]][["Name", "Age"]]  # Accessing specific columns for the first two rows

    Name  Age
0  Alice   25
1    Bob   30

In [34]:
df[df["Age"] > 30]  # Filtering rows where Age is greater than 30

      Name  Age     City  Salary
2  Charlie   35  Chicago   70000