In [1]:
import numpy as np
import pandas as pd

In [7]:
employee = pd.DataFrame({
    'emp_id' : [1, 2, 3, 4,5],
    'emp_name' : ['John', 'Smith', 'Alice', 'Bob','David'],
    'dept_id' : [101, 102, 101, 103,104]
})
#dataframe 2 salary information
salary = pd.DataFrame({
    'emp_id' : [1, 2, 3, 6,7],
        'salary' : [5000, 6000, 7000, 8000,9000],
        'bonus' : [500, 600, 700, 800,900]
})

In [8]:
employee

   emp_id emp_name  dept_id
0       1     John      101
1       2    Smith      102
2       3    Alice      101
3       4      Bob      103
4       5    David      104

In [9]:
salary

   emp_id  salary  bonus
0       1    5000    500
1       2    6000    600
2       3    7000    700
3       6    8000    800
4       7    9000    900

In [10]:
pd.merge(employee, salary)

   emp_id emp_name  dept_id  salary  bonus
0       1     John      101    5000    500
1       2    Smith      102    6000    600
2       3    Alice      101    7000    700

In [ ]:
pd.merge(employee, salary, on='emp_id', how='inner')  # Inner join
#we use inner join to get only the records that have matching values in both dataframes.

   emp_id emp_name  dept_id  salary  bonus
0       1     John      101    5000    500
1       2    Smith      102    6000    600
2       3    Alice      101    7000    700

In [ ]:
pd.merge(employee, salary, on='emp_id', how='outer')  # Outer join
#we use outer join to get all the records from both dataframes. If there is no match, it will fill with NaN.

   emp_id emp_name  dept_id  salary  bonus
0       1     John    101.0  5000.0  500.0
1       2    Smith    102.0  6000.0  600.0
2       3    Alice    101.0  7000.0  700.0
3       4      Bob    103.0     NaN    NaN
4       5    David    104.0     NaN    NaN
5       6      NaN      NaN  8000.0  800.0
6       7      NaN      NaN  9000.0  900.0

In [14]:
df1 = pd.DataFrame({
    'A' : ['A3', 'A4', 'A5', 'A6'],
    'B' : ['B3', 'B4', 'B5', 'B6'],
    'C' : ['C3', 'C4', 'C5', 'C6'],
    'D' : ['D3', 'D4', 'D5', 'D6']
})

df2 = pd.DataFrame({
    'A' : ['A0', 'A1', 'A2', 'A3'],
    'B' : ['B0', 'B1', 'B2', 'B3'],
    'C' : ['C0', 'C1', 'C2', 'C3'],
    'D' : ['D0', 'D1', 'D2', 'D3']
})

In [15]:
df1

    A   B   C   D
0  A3  B3  C3  D3
1  A4  B4  C4  D4
2  A5  B5  C5  D5
3  A6  B6  C6  D6

In [16]:
df2

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [18]:
pd.concat([df1,df2])  # Concatenating along rows

    A   B   C   D
0  A3  B3  C3  D3
1  A4  B4  C4  D4
2  A5  B5  C5  D5
3  A6  B6  C6  D6
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [21]:
a1 = pd.DataFrame({
    'A' : ['A0', 'A1', 'A2', 'A3'],
    'B' : ['B0', 'B1', 'B2', 'B3'],
    'C' : ['C0', 'C1', 'C2', 'C3'],
    'D' : ['D0', 'D1', 'D2', 'D3']
})

a2 = pd.DataFrame({
    'A' : ['A4', 'A5', 'A6', 'A7'],
    'B' : ['B4', 'B5', 'B6', 'B7'],
    'C' : ['C4', 'C5', 'C6', 'C7'],
    'D' : ['D4', 'D5', 'D6', 'D7']
})

In [24]:
a1.join(a2, lsuffix='_left', rsuffix='_right')  # Joining along columns

  A_left B_left C_left D_left A_right B_right C_right D_right
0     A0     B0     C0     D0      A4      B4      C4      D4
1     A1     B1     C1     D1      A5      B5      C5      D5
2     A2     B2     C2     D2      A6      B6      C6      D6
3     A3     B3     C3     D3      A7      B7      C7      D7