In [1]:
import pandas as pd
import numpy as np

In [10]:
#Find missing values in a dataset
data ={
    'A' : [1, 2, np.nan, 4],
    'B' : [np.nan, 2, 3, 4],
    'C' : [1, 2, 1, 4],
    'D' : [np.nan, 2, np.nan, np.nan]
}
dff =pd.DataFrame(data)
dff.isna()  # Checking for missing values in the DataFrame
dff.isna().sum()  # Counting the number of missing values in each column

A    1
B    1
C    0
D    3
dtype: int64

In [12]:
dff.dropna(thresh=1)  # Dropping rows with missing values

     A    B  C    D
0  1.0  NaN  1  NaN
1  2.0  2.0  2  2.0
2  NaN  3.0  1  NaN
3  4.0  4.0  4  NaN

In [ ]:
dff.fillna(0,inplace=True)  # Filling missing values with 0
#we write inplace=True to make changes in the original DataFrame. 
#If we don't write inplace=True, it will return a new DataFrame with missing values filled with 0,
#but the original DataFrame will remain unchanged.

     A    B  C    D
0  1.0  0.0  1  0.0
1  2.0  2.0  2  2.0
2  0.0  3.0  1  0.0
3  4.0  4.0  4  0.0

In [ ]:
values = {'A' : 0, 'B' : 10, 'C' : 100, 'D' : 1000}
dff.fillna(value=values, inplace=True)  # Filling missing values with different values for each column