In [1]:
import numpy as np
import pandas as pd

In [2]:
data = {
    'Date': pd.date_range('2023-01-01', periods=6,),
    'Product': ['A', 'B', 'A', 'B', 'A', 'B'],
    'Region': ['North', 'North', 'South', 'South', 'East', 'East'],
    'Sales': np.random.randint(100, 500, size=6),
    'Units': np.random.randint(1, 10, size=6),
    'Rep': ['John', 'Jane', 'John', 'Jane', 'John', 'Jane']
}

df = pd.DataFrame(data)
df['Month'] = df['Date'].dt.month
df['Year'] = df['Date'].dt.year

In [4]:
df = pd.DataFrame(data)
df

        Date Product Region  Sales  Units   Rep
0 2023-01-01       A  North    246      2  John
1 2023-01-02       B  North    288      7  Jane
2 2023-01-03       A  South    312      4  John
3 2023-01-04       B  South    456      4  Jane
4 2023-01-05       A   East    112      7  John
5 2023-01-06       B   East    119      8  Jane

In [9]:
pd.pivot_table(df, values='Sales', index=['Region'],columns=['Product'], aggfunc=np.sum )

Product    A    B
Region
East     112  119
North    246  288
South    312  456

In [ ]:
#pivot tables are a powerful tool in data analysis that allow you to 
#summarize and aggregate data in a tabular format. They are particularly useful for
#exploring relationships between different variables and for generating insights from large datasets.